- hosts: all
  user: root
  vars:
    rootpw: 'hoge'
  sudo: yes
  tasks:    
    - name: install nginx repository
      yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

    - name: install php & mariadb  
      yum: name={{ item }} state=installed
      with_items:
        - php-mysql
        - php-mbstring
        - php-fpm 
        - php
        - php-gd
        - wget
        - mariadb
        - mariadb-server
        - MySQL-python
        - nginx

    - name: Copy configurationfile 
      copy: src=temp/www.conf dest=/etc/php-fpm.d/ 
      copy: src=temp/default.conf dest=/etc/nginx/conf.d/
      copy: src=temp/my.conf dest=/etc/my.cnf owner=root mode=0600

    - name: enable deamon
      service: name={{ item }} state=started enabled=yes
      with_items:
        - mariadb
        - php-fpm
        - nginx

#2回目以降はコメントアウト
#    - name: rootpass
#      mysql_user: 
#        user: root
#        host: localhost
#        password: hoge

    - name: Create Database
      mysql_db:
        name: wpdb 
        state: present
        login_user: root
        login_password: "{{ rootpw }}"

    - name: user add
      mysql_user: 
        name: n14002
        priv: "*.*:ALL"
        password: 'hoge'
        state: present
        login_user: root
        login_password: hoge 

    - name: Download wordpress
      get_url: 
        url: http://wordpress.org/latest.tar.gz
        dest: /home/vagrant/latest.tar.gz

    - name: Extract archive
      shell: chdir=/usr/share/nginx/ creates=/usr/share/nginx/wordpress /bin/tar xvf /home/vagrant/latest.tar.gz

    - name: Change ownership of WordPress installation
      file:
        path: /usr/share/nginx/wordpress/
        owner: nginx
        group: nginx
        state: directory
        recurse: yes


